<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <h2>Your Activation Code</h2>

        <div>
			Dear {{$username}} : <br/>
            Thank you for creating an account with the Secure chat application.
			To activate your account, you will use the following activation code. <br>
			Your Activation Code : {{$activationcode}}<br/>
			This is a autogenerated mail. Please do not reply to this mail <br/>

        </div>

    </body>
</html>